---
name: Go
on: 
  pull_request:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.18.0-rc.1"]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Set GO
      run: |
        echo "GO=go" >> $GITHUB_ENV

    - name: Verify go mod
      run: make go-mod-verify

    - name: Test
      run: make test

    - name: Crossbuild
      run: make crossbuild
